"""empty message

Revision ID: 010ab4878282
Revises: c27851cb0839
Create Date: 2020-11-02 14:34:45.480490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010ab4878282'
down_revision = 'c27851cb0839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rest_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('init_mood', sa.Integer(), nullable=True),
    sa.Column('end_mood', sa.Integer(), nullable=True),
    sa.Column('content_selected', sa.String(), nullable=True),
    sa.Column('focus_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rest_sessions')
    # ### end Alembic commands ###
