"""empty message

Revision ID: 018af8a22d84
Revises: 5b6e54727fb2
Create Date: 2020-11-20 12:26:51.770102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018af8a22d84'
down_revision = '5b6e54727fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
