"""empty message

Revision ID: 453de40b8a4e
Revises: 
Create Date: 2020-10-25 14:11:47.052358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453de40b8a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('MOVEMENT', 'MEDITATION', 'SOMATIC', name='somaticcategory'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timers')
    op.drop_table('exercises')
    # ### end Alembic commands ###
