"""empty message

Revision ID: 5b6e54727fb2
Revises: 31f98bd19155
Create Date: 2020-11-17 07:19:23.934353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6e54727fb2'
down_revision = '31f98bd19155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timers', sa.Column('mood', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timers', 'mood')
    # ### end Alembic commands ###
