"""empty message

Revision ID: 6b643097f85e
Revises: 225673684e9b
Create Date: 2020-11-25 19:50:33.396907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b643097f85e'
down_revision = '225673684e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rests', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rests', 'users', ['user_id'], ['id'])
    op.add_column('timers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'timers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timers', type_='foreignkey')
    op.drop_column('timers', 'user_id')
    op.drop_constraint(None, 'rests', type_='foreignkey')
    op.drop_column('rests', 'user_id')
    # ### end Alembic commands ###
