"""empty message

Revision ID: 702dcabc038b
Revises: 010ab4878282
Create Date: 2020-11-02 14:35:36.276937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702dcabc038b'
down_revision = '010ab4878282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('init_mood', sa.Integer(), nullable=True),
    sa.Column('end_mood', sa.Integer(), nullable=True),
    sa.Column('content_selected', sa.String(), nullable=True),
    sa.Column('focus_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rest_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rest_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('init_mood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_mood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_selected', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('focus_interval', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rest_interval', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rest_sessions_pkey')
    )
    op.drop_table('rests')
    # ### end Alembic commands ###
