"""empty message

Revision ID: 99e1e86e5fa1
Revises: 702dcabc038b
Create Date: 2020-11-02 15:18:44.534529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e1e86e5fa1'
down_revision = '702dcabc038b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('init_mood', sa.Integer(), nullable=True),
    sa.Column('end_mood', sa.Integer(), nullable=True),
    sa.Column('content_selected', sa.String(), nullable=True),
    sa.Column('focus_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rests')
    # ### end Alembic commands ###
