"""empty message

Revision ID: a3b45635dee3
Revises: 
Create Date: 2020-11-22 17:38:11.083784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b45635dee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('MOVEMENT', 'MEDITATION', 'SOMATIC', name='somaticcategory'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood_rating_1', sa.Integer(), nullable=True),
    sa.Column('mood_rating_2', sa.Integer(), nullable=True),
    sa.Column('content_selected', sa.String(), nullable=True),
    sa.Column('focus_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.Column('sound', sa.String(), nullable=True),
    sa.Column('mood', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timers')
    op.drop_table('users')
    op.drop_table('rests')
    op.drop_table('exercises')
    # ### end Alembic commands ###
