"""empty message

Revision ID: eca4d4b9bdd5
Revises: a3b45635dee3
Create Date: 2020-11-22 18:21:38.379889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca4d4b9bdd5'
down_revision = 'a3b45635dee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rests', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rests', type_='foreignkey')
    op.drop_column('rests', 'user_id')
    # ### end Alembic commands ###
