"""empty message

Revision ID: f5ff70ea61d8
Revises: 
Create Date: 2020-10-22 19:52:10.718931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ff70ea61d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_interval', sa.String(), nullable=True),
    sa.Column('rest_interval', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timers')
    # ### end Alembic commands ###
